#include "arduino_secrets.h"
/*  AUTHOR: Garima (2110994804)
    TASK  : 3.2C "Creating IFTTT Trigger"
*/


// hp_BH1750 - Version: Latest 
#include <hp_BH1750.h>

/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/df6d2fa6-aa11-4f17-9ee1-16c8f5ec2cc8 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float intensity;
  bool sunlight;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

float sensor;
hp_BH1750 BH1750;

void setup() {
  
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  
  pinMode(LED_BUILTIN, OUTPUT);
  
  //setting the address and initializing the light sensor
  bool avail = BH1750.begin(BH1750_TO_GROUND);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}


void loop() {

  ArduinoCloud.update();
  BH1750.start();
  sensor = BH1750.getLux();
  intensity = sensor;
}


/*
  Since Intensity is READ_WRITE variable, onIntensityChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onIntensityChange()  {
  
    if(intensity > 300)
    {
      //Terrarium is exposed to sunlight
      sunlight = true;
      onSunlightChange();
      
      //Print light intensity and sunlight value
      Serial.print("Light intensity: ");
      Serial.print(intensity);
      Serial.println("Sufficient sunlight! ");
    }
    else
    {
      sunlight = false;
      onSunlightChange();
      digitalWrite(LED_BUILTIN, HIGH);
      Serial.print("Light intensity: ");
      Serial.print(intensity);
      Serial.println("Insufficient sunlight! ");
    }
    //Taking a delay of 5 seconds
    delay(5000);
}

/*
  Since Sunlight is READ_WRITE variable, onSunlightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSunlightChange()  {
  if(sunlight = true)
  {
  //Turn led on
  digitalWrite(LED_BUILTIN,HIGH);
  //Give a delay for 2 second
  delay(2000);
  }
  else if(sunlight = false)  
  {
  //Turn led off
  digitalWrite(LED_BUILTIN, LOW);
  //Give a delay for 2 second
  delay(2000);
  }
  
}





