// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onIntensityChange();
void onSunlightChange();

float intensity;
bool sunlight;

void initProperties(){

  ArduinoCloud.addProperty(intensity, READWRITE, ON_CHANGE, onIntensityChange);
  ArduinoCloud.addProperty(sunlight, READWRITE, ON_CHANGE, onSunlightChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
